apiVersion: apps/v1
kind: Deployment
metadata:
  name: XXXX-deployment
  labels:
    app: XXXX
spec:
  replicas: 1
  selector:
    matchLabels:
      app: XXXX
  template:
    metadata:
      labels:
        app: XXXX
    spec:
      containers:
      - name: XXXX
        image: XXXX
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: XXXX-secret
              key: XXXX-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: XXXX-secret
              key: XXXX-root-password

---

apiVersion: v1
kind: Service
metadata:
    name:
        XXXX-service
spec:
    selector:
        app: XXXX
    ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017



